---
- name: Base tasks
  hosts: all
  become: true

  tasks:
    - name: Install base packages
      ansible.builtin.dnf:
        name:
          - htop
          - vim
          - wget
          - fastfetch
          - iperf3

- name: Base config for VMs
  hosts: all:!vps
  become: true

  roles:
    - prometheus.prometheus.node_exporter

  tasks:
    - name: Authorize port 9100 in firewall
      ansible.builtin.firewalld:
        port: 9100/tcp
        permanent: true
        state: enabled

- name: NFS specific packages
  hosts: docker:storage:!vps
  become: true

  tasks:

    - name: Install NFS specific packages
      ansible.builtin.dnf:
        name:
          - nfs-utils
          - rsync

    - name: Start nfs-utils service
      ansible.builtin.service:
        name: nfs-utils
        state: started

    - name: Start rpcbind service
      ansible.builtin.service:
        name: rpcbind
        state: started

    - name: Start nfs-mountd service
      ansible.builtin.service:
        name: nfs-mountd
        state: started
