---
- name: Set DNS server for qual servers
  hosts: qual:!vps
  become: true

  tasks:
    - name: Set DNS server to 192.168.20.254
      ansible.builtin.copy:
        content: "nameserver 192.168.20.254"
        dest: /etc/resolv.conf

- name: Set DNS server for prod servers
  hosts: prod:!vps
  become: true

  tasks:
    - name: Set DNS server to 192.168.10.254
      ansible.builtin.copy:
        content: "nameserver 192.168.10.254"
        dest: /etc/resolv.conf


- name: Base configuration for all servers
  hosts: all
  become: true

  tasks:
    - name: Update packages
      ansible.builtin.apt:
        name: "*"
        state: "latest"

    - name: Install htop
      ansible.builtin.apt:
        name: "htop"
        state: present

    - name: Install vim
      ansible.builtin.apt:
        name: "vim"
        state: present

    - name: Disable SSH root access
      ansible.builtin.replace:
        path: /etc/ssh/sshd_config
        regexp: '^#PermitRootLogin'
        replace: "PermitRootLogin no"
        backup: yes

    - name: Disable SSH password authentication
      ansible.builtin.replace:
        path: /etc/ssh/sshd_config
        regexp: '^#PasswordAuthentication yes'
        replace: "PasswordAuthentication no"
        backup: yes

    - name: Set keyboard to FR
      ansible.builtin.replace:
        path: /etc/default/keyboard
        regexp: '^XKBLAYOUT="us"'
        replace: 'XKBLAYOUT="fr"'

    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted

- name: Install Node Exporter
  hosts: all:!vps
  become: true

  roles:
    - prometheus.prometheus.node_exporter
