---
- name: Configure Prometheus for prod environment
  hosts: vps
  become: true

  tasks:

    - name: Create prometheus config volume
      community.docker.docker_volume:
        name: monitoring_prometheus_config

    - name: Copy prometheus config inside container config volume
      ansible.builtin.copy:
        src: ../../docker/config/prometheus/prometheus.yml
        dest: /var/lib/docker/volumes/monitoring_prometheus_config/_data/
