---
- name: Configure storage server firewall
  hosts: storage
  become: true

  tasks:

    - name: Create multimedia folder
      ansible.builtin.file:
        path: /mnt/Data/Multimedia
        state: directory

    - name: Create multimedia folder
      ansible.builtin.file:
        path: /mnt/Data/Drive
        state: directory

    - name: Copy exports file
      ansible.builtin.template:
        src: templates/nfs_exports.j2
        dest: /etc/exports
        mode: '0644'

    - name: Expose exports file
      ansible.builtin.command:
        cmd: "exportfs -ra"
    
    - name: Open nfs port in firewalld
      ansible.builtin.firewalld:
        service: nfs
        state: enabled
        permanent: true
        immediate: true

    - name: Open rpcbind port in firewalld
      ansible.builtin.firewalld:
        service: rpc-bind
        state: enabled
        permanent: true
        immediate: true

    - name: Open mountd port in firewalld
      ansible.builtin.firewalld:
        service: mountd
        state: enabled
        permanent: true
        immediate: true
