- name: Docker tasks for vps servers
  hosts: qual:&vps
  become: true

  tasks:
    - name: Launch portainer container
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ce
        state: started
        published_ports:
          - '9002:9000'
        volumes:
          - portainer_data:/data
          - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: "unless-stopped"
