- name: Docker tasks for vps servers
  hosts: qual:&vps
  become: true

  tasks:
    - name: Launch portainer container
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ce
        state: started
        published_ports:
          - '9002:9000'
        volumes:
          - portainer_data:/data
          - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: "unless-stopped"

    - name: Create headscale_config Docker volume
      community.docker.docker_volume:
        name: headscale_config

    - name: Copy headscale config in volume
      ansible.builtin.template:
        src: ../../../docker/config/headscale/config.yaml.j2
        dest: /var/lib/docker/volumes/headscale_config/_data/config.yaml

    - name: Create headplane_config Docker volume
      community.docker.docker_volume:
        name: headplane_config

    - name: Copy headplane config in volume
      ansible.builtin.template:
        src: ../../../docker/config/headplane/config.yaml.j2
        dest: /var/lib/docker/volumes/headplane_config/_data/config.yaml
