---
- name: Configure VMs in Proxmox
  hosts: proxmox
  become: true

  tasks:
    - name: Update DNS servers
      ansible.builtin.copy:
        content: "nameserver 192.168.10.254"
        dest: /etc/resolv.conf
