---
- name: Mount NFS parition for qual Docker server
  hosts: qual:&docker:!vps
  become: true

  tasks:
    - name: Install NFS packages
      ansible.builtin.apt:
        name: nfs-common
        state: present

    - name: Mount NFS partition
      ansible.posix.mount:
        path: /mnt/Data
        src: 192.168.20.251:/mnt/Data
        fstype: nfs
        state: mounted

