---
- name: Configure compute server
  hosts: services
  become: true

  tasks:
    - name: Update packages
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Install keyrings
      ansible.builtin.command:
        cmd: "install -m 0755 -d /etc/apt/keyrings"

    - name: Add Docker repo
      ansible.builtin.deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux/debian
        suites: '{{ ansible_distribution_release }}'
        components: stable
        architectures: amd64
        signed_by: https://download.docker.com/linux/debian/gpg
    
    - name: Update apt and install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

- name: Mount NFS drive and launch Portainer container for SRV-01 server
  hosts: SRV-QUAL-01
  become: true

  tasks:
    - name: Launch portainer container
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ce
        state: started
        published_ports:
          - '{{ ansible_facts.eth1.ipv4.address }}:9443:9443'
        volumes:
          - portainer_data:/data
          - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: "unless-stopped"
 
- name: Launch Portainer agent for VPS-01 server
  hosts: VPS-QUAL-01
  become: true

  tasks:
    - name: Launch Portainer agent container
      community.docker.docker_container:
        name: portainer-agent
        image: portainer/agent
        state: started
        published_ports:
          - 9001:9001
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volumes:/var/lib/docker/volumes
        restart_policy: "unless-stopped"
