- name: Docker tasks for vps servers
  hosts: vps
  become: true

  tasks:
    - name: Launch Portainer agent container
      community.docker.docker_container:
        name: portainer-agent
        image: portainer/agent
        state: started
        published_ports:
          - 9001:9001
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volumes:/var/lib/docker/volumes
        restart_policy: "unless-stopped"

    - name: Create headscale_config Docker volume
      community.docker.docker_volume:
        name: headscale_config

    - name: Copy headscale config in volume
      ansible.builtin.template:
        src: ../../../docker/config/headscale/config.yaml.j2
        dest: /var/lib/docker/volumes/headscale_config/_data/config.yaml

    - name: Create headplane_config Docker volume
      community.docker.docker_volume:
        name: headplane_config

    - name: Copy headplane config in volume
      ansible.builtin.template:
        src: ../../../docker/config/headplane/config.yaml.j2
        dest: /var/lib/docker/volumes/headplane_config/_data/config.yaml
