services:
  media:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    hostname: media
    ports:
      - 8083:8096
    volumes:
      - jellyfin_config:/config
      - /mnt/Data/Multimedia/Medias:/media
    networks:
      - front

  torrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
      - WEBUI_PORT=8084
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    ports:
      - 8084:8084
    volumes:
      - qbittorrent_config:/config
      - /mnt/Data/Multimedia/Downloads:/downloads
    networks:
      - front

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - sonarr_config:/config
      - /mnt/Data/Multimedia/Medias/Series:/media/Series
      - /mnt/Data/Multimedia/Medias/Animes:/media/Animes
      - /mnt/Data/Multimedia/Downloads/series:/mnt/Downloads/series
      - /mnt/Data/Multimedia/Downloads/animes:/mnt/Downloads/animes
    ports:
      - 8085:8989
    networks:
      - front

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - radarr_config:/config
      - /mnt/Data/Multimedia/Medias/Films:/media/Films
      - /mnt/Data/Multimedia/Downloads/films:/mnt/Downloads/films
    ports:
      - 8086:7878
    networks:
      - front

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - lidarr_config:/config
      - /mnt/Data/Multimedia/Medias/Music:/media/Music
      - /mnt/Data/Multimedia/Downloads/music:/mnt/Downloads/music
    ports:
      - 8087:8686
    networks:
      - front

  navidrome:
    image: deluan/navidrome
    container_name: navidrome
    ports:
      - 8088:4533
    volumes:
      - navidrome_data:/data
      - /mnt/Data/Multimedia/Medias/Music:/music:ro
    networks:
      - front

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    volumes:
      - prowlarr_config:/config
    ports:
      - 8089:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    networks:
      - front

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr
    container_name: flaresolverr
    ports:
      - 8090:8191
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
    networks:
      - front

  jellyseerr:
    image: fallenbagel/jellyseerr:preview-OIDC
    container_name: jellyseerr
    ports:
      - 8091:5055
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped
    volumes:
      - jellyseerr_config:/app/config
    networks:
      - front


networks:
  front:
    external: true

volumes:
  jellyfin_config:
  qbittorrent_config:
  sonarr_config:
  radarr_config:
  lidarr_config:
  navidrome_data:
  prowlarr_config:
  jellyseerr_config:
