services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: always
    ports:
      - 3001:3001
    volumes:
      - uptime-kuma_data:/app/data
    networks:
      - front

volumes:
  uptime-kuma_data:

networks:
  front:
    external: true
