services:
  traefik:
    image: traefik
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.defaultRule=Host(`{{trimPrefix '/' .Name}}.docker.localhost`)"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    networks:
      - front
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.${BASE_HOST}`)
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.service=api@internal

networks:
  front:
    external: true
