services:
  vault:
    image: vaultwarden/server
    container_name: vault
    restart: unless-stopped
    volumes:
      - vault_data:/data
    ports:
      - 8081:80
    networks:
      - front

  librespeed:
    image: lscr.io/linuxserver/librespeed
    container_name: librespeed
    restart: unless-stopped
    ports:
      - 8082:80
    networks:
      - front

volumes:
  vault_data:

networks:
  front:
    external: true
