---
- name: Base configuration for all servers
  hosts: all
  become: true

  pre_tasks:
    - name: Update DNS servers to 9.9.9.9
      ansible.builtin.copy:
        content: "nameserver 9.9.9.9"
        dest: /etc/resolv.conf

  roles:
    - prometheus.prometheus.node_exporter

  tasks:
    - name: Update packages
      ansible.builtin.apt:
        name: "*"
        state: "latest"

    - name: Install htop
      ansible.builtin.apt:
        name: "htop"
        state: present

    - name: Install vim
      ansible.builtin.apt:
        name: "vim"
        state: present

    - name: Disable SSH root access
      ansible.builtin.replace:
        path: /etc/ssh/sshd_config
        regexp: '^#PermitRootLogin'
        replace: "PermitRootLogin no"
        backup: yes

    - name: Disable SSH password authentication
      ansible.builtin.replace:
        path: /etc/ssh/sshd_config
        regexp: '^#PasswordAuthentication yes'
        replace: "PasswordAuthentication no"
        backup: yes

    - name: Set keyboard to FR
      ansible.builtin.replace:
        path: /etc/default/keyboard
        regexp: '^XKBLAYOUT="us"'
        replace: 'XKBLAYOUT="fr"'

    - name: Set hostname
      ansible.builtin.hostname:
        name: '{{ ansible_facts.hostname }}'

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted

    - name: Reboot host
      ansible.builtin.reboot:
        
